[package]
name = "yandex-music-player"
version = "0.1.0"
description = "Modern music player with multiple streaming services support"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.6", features = ["api-all", "system-tray"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
rodio = "0.17"
config = "0.13"
toml = "0.8"
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
futures = "0.3"
uuid = { version = "1.0", features = ["v4"] }
base64 = "0.21"
url = "2.4"
dirs = "5.0"
async-trait = "0.1"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]

[[bin]]
name = "yandex-music-player"
path = "src/main.rs"
